version: 1.2
workflows:
name: fullMitoPipeline_v2_6_Multi
 - subclass: WDL
   primaryDescriptorPath: fullMitoPipeline_v2_6_Multi.wdl

name: Create AlignAndCallR1_v2_6_Multi
 - subclass: WDL
   primaryDescriptorPath: AlignAndCallR1_v2_6_Multi.wdl
name: Create AlignAndCallR2_v2_6_Multi
 - subclass: WDL
   primaryDescriptorPath: AlignAndCallR2_v2_6_Multi.wdl
name: LiftoverTools_v2_6_Multi
 - subclass: WDL
   primaryDescriptorPath: LiftoverTools_v2_6_Multi.wdl
name: MongoTasks_v2_6_Multi
 - subclass: WDL
   primaryDescriptorPath: MongoTasks_v2_6_Multi.wdl
name: ProduceSelfReferenceFiles_v2_6_Multi
 - subclass: WDL
   primaryDescriptorPath: ProduceSelfReferenceFiles_v2_6_Multi.wdl
